DROP TABLE Persona;
CREATE TABLE Persona (
    idPersona      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre         VARCHAR2(100) NOT NULL,
    apellido       VARCHAR2(100) NOT NULL,
    direccion      VARCHAR2(200),
    telefono       VARCHAR2(20),
    email          VARCHAR2(100),
    CONSTRAINT pk_persona PRIMARY KEY (idPersona)
);
SELECT * FROM Persona;
-- Subtipos

-- Alumno
DROP TABLE Alumno;
CREATE TABLE Alumno (
    idPersona          NUMBER,
    idCentroEducativo  NUMBER NOT NULL,
    numExpediente      VARCHAR2(30) UNIQUE NOT NULL,
    idTitulacion       NUMBER,
    CONSTRAINT pk_alumno PRIMARY KEY (idPersona),
    CONSTRAINT fk_alumno_persona FOREIGN KEY (idPersona)
        REFERENCES Persona (idPersona)
        ON DELETE CASCADE
);

-- Profesor
CREATE TABLE Profesor (
    idPersona        NUMBER,
    idDepartamento   NUMBER NOT NULL,
    dedicacion       VARCHAR2(50),
    CONSTRAINT pk_profesor PRIMARY KEY (idPersona),
    CONSTRAINT fk_profesor_persona FOREIGN KEY (idPersona)
        REFERENCES Persona (idPersona)
        ON DELETE CASCADE
);

-- Administrativo
CREATE TABLE Administrativo (
    idPersona             NUMBER,
    idUnidadAdministrativa NUMBER NOT NULL,
    categoriaProfesional  VARCHAR2(50),
    CONSTRAINT pk_administrativo PRIMARY KEY (idPersona),
    CONSTRAINT fk_adm_persona FOREIGN KEY (idPersona)
        REFERENCES Persona (idPersona)
        ON DELETE CASCADE
);

-- Tablas independientes
-- Centro Educativo
CREATE TABLE CentroEducativo (
    idCentro   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre     VARCHAR2(150) NOT NULL,
    CONSTRAINT pk_centro PRIMARY KEY (idCentro)
);

-- Departamento
CREATE TABLE Departamento (
    idDepartamento  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre          VARCHAR2(150) NOT NULL,
    CONSTRAINT pk_departamento PRIMARY KEY (idDepartamento)
);

-- Títulos
CREATE TABLE Titulos (
    idTitulo  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre    VARCHAR2(150) NOT NULL,
    CONSTRAINT pk_titulo PRIMARY KEY (idTitulo)
);

-- Unidad Administrativa
CREATE TABLE UnidadAdministrativa (
    idUnidadAdministrativa NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre                 VARCHAR2(150) NOT NULL,
    idCentroEducativo      NUMBER NOT NULL,
    CONSTRAINT pk_unidad_admin PRIMARY KEY (idUnidadAdministrativa),
    CONSTRAINT fk_unidad_centro FOREIGN KEY (idCentroEducativo)
        REFERENCES CentroEducativo (idCentro)
);

-- Tablas de relaciones
-- Relación N:M Profesor - CentroEducativo
CREATE TABLE Profesor_CentroEducativo (
    idProfesor       NUMBER NOT NULL,
    idCentroEducativo NUMBER NOT NULL,
    CONSTRAINT pk_prof_centro PRIMARY KEY (idProfesor, idCentroEducativo),
    CONSTRAINT fk_prof_centro_prof FOREIGN KEY (idProfesor)
        REFERENCES Profesor (idPersona),
    CONSTRAINT fk_prof_centro_centro FOREIGN KEY (idCentroEducativo)
        REFERENCES CentroEducativo (idCentro)
);

-- Agregar claves foráneas faltantes
-- Alumno -> CentroEducativo
DROP TABLE Alumno;
ALTER TABLE Alumno
ADD CONSTRAINT fk_alumno_centro FOREIGN KEY (idCentroEducativo)
    REFERENCES CentroEducativo (idCentro);

-- Alumno -> Títulos
ALTER TABLE Alumno
ADD CONSTRAINT fk_alumno_titulo FOREIGN KEY (idTitulacion)
    REFERENCES Titulos (idTitulo);

-- Profesor -> Departamento
ALTER TABLE Profesor
ADD CONSTRAINT fk_profesor_dep FOREIGN KEY (idDepartamento)
    REFERENCES Departamento (idDepartamento);
    

-- Administrativo -> Unidad Administrativa
ALTER TABLE Administrativo
ADD CONSTRAINT fk_adm_unidad FOREIGN KEY (idUnidadAdministrativa)
    REFERENCES UnidadAdministrativa (idUnidadAdministrativa);
    

--Vista
CREATE OR REPLACE VIEW vPersonasUniversidad AS
SELECT 
    p.idPersona,
    p.nombre,
    p.apellido,
    p.dni,
    p.fecha_nac,
    'ALUMNO' AS tipoPersona,
    a.numExpediente AS dato1,
    ce.nombre AS centro_o_depto,
    t.nombre AS titulo_o_categoria
FROM Persona p
JOIN Alumno a ON p.idPersona = a.idPersona
LEFT JOIN CentroEducativo ce ON a.idCentroEducativo = ce.idCentro
LEFT JOIN Titulos t ON a.idTitulacion = t.idTitulo

UNION ALL

SELECT 
    p.idPersona,
    p.nombre,
    p.apellido,
    p.dni,
    p.fecha_nac,
    'PROFESOR' AS tipoPersona,
    pr.categoria AS dato1,
    d.nombre AS centro_o_depto,
    NULL AS titulo_o_categoria
FROM Persona p
JOIN Profesor pr ON p.idPersona = pr.idPersona
LEFT JOIN Departamento d ON pr.idDepartamento = d.idDepartamento

UNION ALL

SELECT 
    p.idPersona,
    p.nombre,
    p.apellido,
    p.dni,
    p.fecha_nac,
    'ADMINISTRATIVO' AS tipoPersona,
    ad.cargo AS dato1,
    ua.nombre AS centro_o_depto,
    NULL AS titulo_o_categoria
FROM Persona p
JOIN Administrativo ad ON p.idPersona = ad.idPersona
LEFT JOIN UnidadAdministrativa ua ON ad.idUnidadAdministrativa = ua.idUnidadAdministrativa
ORDER BY apellido, nombre;

-- Índice general sobre nombre en Persona
CREATE INDEX idx_persona_nombre ON Persona(nombre);




