-- Creación de la tabla EMPLEADOS
CREATE TABLE EMPLEADOS (
    DNI             NUMBER(8) PRIMARY KEY,
    NOMBRE          VARCHAR(10) NOT NULL,
    APELLIDO1       VARCHAR(15) NOT NULL,
    APELLIDO2       VARCHAR(15),
    DIRECC1         VARCHAR(25),
    DIRECC2         VARCHAR(20),
    CIUDAD          VARCHAR(20),
    PROVINCIA       VARCHAR(20),
    COD_POSTAL      VARCHAR(5),
    SEXO            VARCHAR(1),
    FECHA_NAC       DATE
);

-- Creación de la tabla DEPARTAMENTOS
CREATE TABLE DEPARTAMENTOS (
    DPTO_COD        NUMBER(5) PRIMARY KEY,
    NOMBRE_DPTO     VARCHAR(30) NOT NULL,
    DPTO_PADRE      NUMBER(5),
    PRESUPUESTO     NUMBER NOT NULL,
    PRES_ACTUAL     NUMBER,
    FOREIGN KEY (DPTO_PADRE) REFERENCES DEPARTAMENTOS(DPTO_COD)
);

-- Creación de la tabla UNIVERSIDADES
CREATE TABLE UNIVERSIDADES (
    UNIV_COD        NUMBER(5) PRIMARY KEY,
    NOMBRE_UNIV     VARCHAR(25) NOT NULL,
    CIUDAD          VARCHAR(20),
    MUNICIPIO       VARCHAR(2),
    COD_POSTAL      VARCHAR(5)
);

-- Creación de la tabla ESTUDIOS
CREATE TABLE ESTUDIOS (
    EMPLEADO_DNI    NUMBER(8) NOT NULL,
    UNIVERSIDAD     NUMBER(5) NOT NULL,
    AÑO             NUMBER,
    GRADO           VARCHAR(3),
    ESPECIALIDAD    VARCHAR(20),
    PRIMARY KEY (EMPLEADO_DNI, UNIVERSIDAD),
    FOREIGN KEY (EMPLEADO_DNI) REFERENCES EMPLEADOS(DNI),
    FOREIGN KEY (UNIVERSIDAD) REFERENCES UNIVERSIDADES(UNIV_COD)
);

-- Creación de la tabla TRABAJOS
CREATE TABLE TRABAJOS (
    TRABAJO_COD     NUMBER(5) PRIMARY KEY,
    NOMBRE_TRAB     VARCHAR(20) NOT NULL,
    SALARIO_MIN     NUMBER(2) NOT NULL,
    SALARIO_MAX     NUMBER(2) NOT NULL
);

-- Creación de la tabla HISTORIAL_LABORAL
CREATE TABLE HISTORIAL_LABORAL (
    EMPLEADO_DNI    NUMBER(8) NOT NULL,
    TRABAJO_COD     NUMBER(5) NOT NULL,
    FECHA_INICIO    DATE NOT NULL,
    FECHA_FIN       DATE,
    DPTO_COD        NUMBER(5),
    SUPERVISOR_DNI  NUMBER(8),
    PRIMARY KEY (EMPLEADO_DNI, TRABAJO_COD, FECHA_INICIO),
    FOREIGN KEY (EMPLEADO_DNI) REFERENCES EMPLEADOS(DNI),
    FOREIGN KEY (TRABAJO_COD) REFERENCES TRABAJOS(TRABAJO_COD),
    FOREIGN KEY (DPTO_COD) REFERENCES DEPARTAMENTOS(DPTO_COD),
    FOREIGN KEY (SUPERVISOR_DNI) REFERENCES EMPLEADOS(DNI)
);

-- Creación de la tabla HISTORIAL_SALARIAL
CREATE TABLE HISTORIAL_SALARIAL (
    EMPLEADO_DNI    NUMBER(8) NOT NULL,
    SALARIO         NUMBER NOT NULL,
    FECHA_COMIENZO  DATE NOT NULL,
    FECHA_FIN       DATE,
    PRIMARY KEY (EMPLEADO_DNI, FECHA_COMIENZO),
    FOREIGN KEY (EMPLEADO_DNI) REFERENCES EMPLEADOS(DNI)
);

-- 2.- 
ALTER TABLE EMPLEADOS
ADD CONSTRAINT CHK_SEXO CHECK (SEXO IN ('H', 'M'));

--3.-Restricción para nombres únicos de DEPARTAMENTOS y TRABAJOS:
ALTER TABLE DEPARTAMENTOS
ADD CONSTRAINT UQ_NOMBRE_DPTO UNIQUE (NOMBRE_DPTO);

ALTER TABLE TRABAJOS
ADD CONSTRAINT UQ_NOMBRE_TRAB UNIQUE (NOMBRE_TRAB);

-- 6.- Agregar campos de teléfono y celular a la tabla EMPLEADOS:
ALTER TABLE EMPLEADOS
ADD (TELEFONO VARCHAR(15), CELULAR VARCHAR(15));

--7.- 
-- Inserción en TRABAJOS (ejemplo)
INSERT INTO TRABAJOS (TRABAJO_COD, NOMBRE_TRAB, SALARIO_MIN, SALARIO_MAX)
VALUES (100, 'Programador', 15, 30);
INSERT INTO TRABAJOS (TRABAJO_COD, NOMBRE_TRAB, SALARIO_MIN, SALARIO_MAX)
VALUES (200, 'Analista', 25, 45);

-- Inserción en DEPARTAMENTOS (ejemplo)
INSERT INTO DEPARTAMENTOS (DPTO_COD, NOMBRE_DPTO, PRESUPUESTO)
VALUES (10, 'Desarrollo', 100000);
INSERT INTO DEPARTAMENTOS (DPTO_COD, NOMBRE_DPTO, PRESUPUESTO)
VALUES (20, 'Recursos Humanos', 50000);

-- Inserción en EMPLEADOS
INSERT INTO EMPLEADOS (DNI, NOMBRE, APELLIDO1, APELLIDO2, SEXO)
VALUES (111222, 'Sergio', 'Palma', 'Ruiz', 'H');
INSERT INTO EMPLEADOS (DNI, NOMBRE, APELLIDO1, APELLIDO2, SEXO)
VALUES (222333, 'Lucia', 'Ortega', 'Merino', 'M');
--Inserción Historial Laboral
INSERT INTO HISTORIAL_LABORAL (EMPLEADO_DNI, TRABAJO_COD, FECHA_INICIO, DPTO_COD, SUPERVISOR_DNI)
VALUES (111222, 100, TO_DATE('16/06/1996', 'DD/MM/YYYY'), 10, 222333);

SELECT * FROM EMPLEADOS;
SELECT * FROM HISTORIAL_LABORAL;



--8.- 
UPDATE HISTORIAL_LABORAL
SET SUPERVISOR_DNI = 999999
WHERE EMPLEADO_DNI = 111222;

--9.-
-- Inserción en UNIVERSIDADES
INSERT INTO UNIVERSIDADES (UNIV_COD, NOMBRE_UNIV)
VALUES (1, 'UNMSM');

-- Inserción en ESTUDIOS
INSERT INTO ESTUDIOS (EMPLEADO_DNI, UNIVERSIDAD, AÑO, GRADO, ESPECIALIDAD)
VALUES (111222, 1, 2000, 'ING', 'Software');

DELETE FROM UNIVERSIDADES WHERE UNIV_COD = 1;


ALTER TABLE ESTUDIOS
DROP CONSTRAINT SYS_C008275;

ALTER TABLE ESTUDIOS
ADD CONSTRAINT FK_UNIVERSIDAD_ESTUDIOS
FOREIGN KEY (UNIVERSIDAD) REFERENCES UNIVERSIDADES(UNIV_COD) ON DELETE CASCADE;

--10.-
ALTER TABLE EMPLEADOS
ADD CONSTRAINT CHK_CIUDAD_COD_POSTAL
CHECK ( (CIUDAD IS NULL) OR (CIUDAD IS NOT NULL AND COD_POSTAL IS NOT NULL) );

--11.-
ALTER TABLE EMPLEADOS
ADD (VALORACION NUMBER(2) DEFAULT 5);

ALTER TABLE EMPLEADOS
ADD CONSTRAINT CHK_VALORACION
CHECK (VALORACION BETWEEN 1 AND 10);

-- 12.-
ALTER TABLE EMPLEADOS
MODIFY NOMBRE VARCHAR(10) NULL;

-- 13.-
ALTER TABLE EMPLEADOS
MODIFY DIRECC1 VARCHAR(40);


--15.-
ALTER TABLE EMPLEADOS
ADD CONSTRAINT PK_EMPLEADOS_NOMBRE_APE PRIMARY KEY (NOMBRE, APELLIDO1, APELLIDO2);

-- 16.-
CREATE TABLE INFORMACION_UNIVERSITARIA (
    NOMBRE_COMPLETO VARCHAR(50), 
    UNIVERSIDAD_NOMBRE VARCHAR(25)
);

INSERT INTO INFORMACION_UNIVERSITARIA (NOMBRE_COMPLETO, UNIVERSIDAD_NOMBRE)
SELECT
    e.NOMBRE || ' ' || e.APELLIDO1 || ' ' || e.APELLIDO2 AS NOMBRE_COMPLETO,
    u.NOMBRE_UNIV AS UNIVERSIDAD_NOMBRE
FROM
    EMPLEADOS e
JOIN
    ESTUDIOS es ON e.DNI = es.EMPLEADO_DNI
JOIN
    UNIVERSIDADES u ON es.UNIVERSIDAD = u.UNIV_COD;
    
--17.-
CREATE VIEW NOMBRE_EMPLEADOS AS
SELECT
    NOMBRE || ' ' || APELLIDO1 || ' ' || APELLIDO2 AS NOMBRE_COMPLETO
FROM
    EMPLEADOS
WHERE
    CIUDAD = 'Málaga';
    
--18.-
CREATE VIEW INFORMACION_EMPLEADOS AS
SELECT
    NOMBRE || ' ' || APELLIDO1 || ' ' || APELLIDO2 AS NOMBRE_COMPLETO,
    TRUNC(MONTHS_BETWEEN(SYSDATE, FECHA_NAC) / 12) AS EDAD
FROM
    EMPLEADOS;

--19.-
CREATE OR REPLACE VIEW INFORMACION_ACTUAL AS
SELECT
    ie.NOMBRE_COMPLETO,
    ie.EDAD,
    hs.SALARIO
FROM
    INFORMACION_EMPLEADOS ie
JOIN EMPLEADOS e
    ON ie.NOMBRE_COMPLETO = (e.NOMBRE || ' ' || e.APELLIDO1 || ' ' || e.APELLIDO2)
JOIN (
    SELECT EMPLEADO_DNI, SALARIO
    FROM (
        SELECT 
            EMPLEADO_DNI,
            SALARIO,
            ROW_NUMBER() OVER (PARTITION BY EMPLEADO_DNI ORDER BY FECHA_COMIENZO DESC) AS rn
        FROM HISTORIAL_SALARIAL
    )
    WHERE rn = 1
) hs
    ON e.DNI = hs.EMPLEADO_DNI;
