--------------------------------------------------------------------------------
-- [3] TABLAS Y CONSTRAINTS
--------------------------------------------------------------------------------

-- Tabla EQUIPO
CREATE TABLE EQUIPO (
    id_equipo     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre        VARCHAR2(100) NOT NULL,
    nacionalidad  VARCHAR2(50),
    director      VARCHAR2(100),
    CONSTRAINT pk_equipo PRIMARY KEY (id_equipo),
    CONSTRAINT uq_equipo_nombre UNIQUE (nombre)
) TABLESPACE ciclismo_data;

-- Tabla CICLISTA
CREATE TABLE CICLISTA (
    id_ciclista     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre          VARCHAR2(100) NOT NULL,
    nacionalidad    VARCHAR2(50),
    fecha_nac       DATE,
    id_equipo       NUMBER NOT NULL,
    inicio_contrato DATE,
    fin_contrato    DATE,
    CONSTRAINT pk_ciclista PRIMARY KEY (id_ciclista),
    CONSTRAINT fk_ciclista_equipo FOREIGN KEY (id_equipo)
        REFERENCES EQUIPO(id_equipo)
        ON DELETE CASCADE,
    CONSTRAINT ck_ciclista_contrato CHECK (
        (inicio_contrato IS NULL AND fin_contrato IS NULL)
        OR (inicio_contrato IS NOT NULL AND fin_contrato IS NULL)
        OR (inicio_contrato IS NOT NULL AND fin_contrato >= inicio_contrato)
    )
) TABLESPACE ciclismo_data;

-- Tabla PRUEBA
CREATE TABLE PRUEBA (
    id_prueba    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre       VARCHAR2(100) NOT NULL,
    anio         NUMBER(4) NOT NULL,
    etapas       NUMBER,
    km_totales   NUMBER,
    ganador      NUMBER,
    CONSTRAINT pk_prueba PRIMARY KEY (id_prueba),
    CONSTRAINT ck_prueba_anio CHECK (anio BETWEEN 1900 AND 2100),
    CONSTRAINT ck_prueba_etapas CHECK (etapas IS NULL OR etapas > 0),
    CONSTRAINT ck_prueba_km CHECK (km_totales IS NULL OR km_totales > 0),
    CONSTRAINT fk_prueba_ganador FOREIGN KEY (ganador)
        REFERENCES CICLISTA(id_ciclista)
        ON DELETE SET NULL
) TABLESPACE ciclismo_data;

-- Tabla PARTICIPACION
CREATE TABLE PARTICIPACION (
    id_equipo    NUMBER NOT NULL,
    id_prueba    NUMBER NOT NULL,
    puesto_final NUMBER,
    CONSTRAINT pk_participacion PRIMARY KEY (id_equipo, id_prueba),
    CONSTRAINT fk_part_equipo FOREIGN KEY (id_equipo)
        REFERENCES EQUIPO(id_equipo)
        ON DELETE CASCADE,
    CONSTRAINT fk_part_prueba FOREIGN KEY (id_prueba)
        REFERENCES PRUEBA(id_prueba)
        ON DELETE CASCADE,
    CONSTRAINT ck_puesto_final CHECK (puesto_final IS NULL OR puesto_final >= 1)
) TABLESPACE ciclismo_data;

--------------------------------------------------------------------------------
-- [4] ÍNDICES
--------------------------------------------------------------------------------
CREATE INDEX ix_ciclista_equipo ON CICLISTA(id_equipo);
CREATE INDEX ix_prueba_ganador ON PRUEBA(ganador);
CREATE INDEX ix_participacion_prueba ON PARTICIPACION(id_prueba);