--------------------------------------------------------------------------------
-- Tablas auxiliares requeridas por el laboratorio
--------------------------------------------------------------------------------

-- HORARIO: día, turno, hora inicio/fin 
CREATE TABLE HORARIO (
  DIA_DE_LA_SEMANA   VARCHAR2(10)   NOT NULL,
  TURNO              VARCHAR2(10)   NOT NULL,
  HORA_INICIO        VARCHAR2(8)    NOT NULL, -- 'HH24:MI:SS'
  HORA_TERMINO       VARCHAR2(8)    NOT NULL, -- 'HH24:MI:SS'
  CONSTRAINT PK_HORARIO PRIMARY KEY (DIA_DE_LA_SEMANA, TURNO)
);

-- EMPLEADO_HORARIO: asignación de horario por empleado
CREATE TABLE EMPLEADO_HORARIO (
  EMPLOYEE_ID        NUMBER         NOT NULL,
  DIA_DE_LA_SEMANA   VARCHAR2(10)   NOT NULL,
  TURNO              VARCHAR2(10)   NOT NULL,
  CONSTRAINT PK_EMPLEADO_HORARIO PRIMARY KEY (EMPLOYEE_ID, DIA_DE_LA_SEMANA, TURNO)
);

-- ASISTENCIA_EMPLEADO: registro de asistencia del empleado
CREATE TABLE ASISTENCIA_EMPLEADO (
  EMPLOYEE_ID        NUMBER         NOT NULL,
  DIA_DE_LA_SEMANA   VARCHAR2(10)   NOT NULL,
  FECHA_REAL         DATE           NOT NULL,
  HORA_INICIO_REAL   TIMESTAMP      NOT NULL,
  HORA_TERMINO_REAL  TIMESTAMP      NOT NULL
);

-- CAPACITACION: catálogo de capacitaciones
CREATE TABLE CAPACITACION (
  CAPACITACION_ID      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  NOMBRE               VARCHAR2(100) NOT NULL,
  HORAS_CAPACITACION   NUMBER        NOT NULL,
  DESCRIPCION          VARCHAR2(4000)
);

-- EMPLEADO_CAPACITACION: relación empleado-capacitación
CREATE TABLE EMPLEADO_CAPACITACION (
  EMPLOYEE_ID       NUMBER        NOT NULL,
  CAPACITACION_ID   NUMBER        NOT NULL,
  CONSTRAINT PK_EMPLEADO_CAP PRIMARY KEY (EMPLOYEE_ID, CAPACITACION_ID),
  CONSTRAINT FK_EMPLEADO_CAP_CAP FOREIGN KEY (CAPACITACION_ID) REFERENCES CAPACITACION(CAPACITACION_ID)
);

-- INASISTENCIAS_LOG: auditoría de registros fuera de la ventana permitida
CREATE TABLE INASISTENCIAS_LOG (
  LOG_ID          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  EMPLOYEE_ID     NUMBER,
  FECHA           DATE,
  HORA_REGISTRO   TIMESTAMP,
  HORA_ESPERADA   VARCHAR2(50),
  DIFERENCIA_MIN  NUMBER,
  MOTIVO          VARCHAR2(200),
  CREADO_EN       DATE DEFAULT SYSDATE
);

--------------------------------------------------------------------------------
-- Paquete: PKG_EMPLOYEE_MGMT
--------------------------------------------------------------------------------
CREATE OR REPLACE PACKAGE PKG_EMPLOYEE_MGMT AS
  -- 3.1.1
  PROCEDURE sp_top_rotaciones(p_cantidad IN INTEGER);
  -- 3.1.2
  FUNCTION fn_promedio_contrataciones RETURN NUMBER;
  -- 3.1.3
  PROCEDURE sp_resumen_regional;
  -- 3.1.4
  FUNCTION fn_tiempo_servicio RETURN NUMBER;
  -- 3.1.5
  FUNCTION fn_horas_trabajadas_mes(p_employee_id INTEGER, p_month INTEGER, p_year INTEGER) RETURN NUMBER;
  -- 3.1.6
  FUNCTION fn_horas_faltantes_mes(p_employee_id INTEGER, p_mes NUMBER, p_anio NUMBER) RETURN NUMBER;
  -- 3.1.7
  PROCEDURE sp_reporte_salarios_mes(p_mes NUMBER, p_anio NUMBER);
  -- 3.1.1 (sección de capacitación del enunciado)
  FUNCTION fn_total_horas_capacitacion(p_employee_id IN NUMBER) RETURN NUMBER;
  -- 3.1.2 (sección de capacitación del enunciado)
  PROCEDURE sp_listar_capacitaciones;
END PKG_EMPLOYEE_MGMT;
/

CREATE OR REPLACE PACKAGE BODY PKG_EMPLOYEE_MGMT AS

  -- sp_top_rotaciones: top N empleados por cantidad de cambios en JOB_HISTORY
  PROCEDURE sp_top_rotaciones(p_cantidad IN INTEGER) AS
    CURSOR c_top IS
      SELECT
        e.employee_id  codigo,
        e.last_name    apellido,
        e.first_name   nombre,
        j.job_id       codigo_puesto,
        j.job_title    nombre_puesto,
        COUNT(jh.job_id) cantidad_rotaciones
      FROM employees e
      JOIN job_history jh ON e.employee_id = jh.employee_id
      JOIN jobs j ON e.job_id = j.job_id
      GROUP BY e.employee_id, e.last_name, e.first_name, j.job_id, j.job_title
      ORDER BY cantidad_rotaciones DESC
      FETCH FIRST p_cantidad ROWS ONLY;
  BEGIN
    FOR r IN c_top LOOP
      DBMS_OUTPUT.PUT_LINE(
        'Codigo: '||r.codigo||', Apellido: '||r.apellido||', Nombre: '||r.nombre||
        ', Codigo del puesto: '||r.codigo_puesto||', Nombre del puesto: '||r.nombre_puesto||
        ', Cantidad de rotaciones: '||r.cantidad_rotaciones
      );
    END LOOP;
  END sp_top_rotaciones;

  -- fn_promedio_contrataciones: resumen por mes y retorna # de meses listados
  FUNCTION fn_promedio_contrataciones RETURN NUMBER AS
    v_cnt_meses NUMBER := 0;
  BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10)||'--- Resumen Estadístico de Contrataciones ---');
    DBMS_OUTPUT.PUT_LINE('----------------------------------------------------');
    DBMS_OUTPUT.PUT_LINE('Nombre del Mes | Número Promedio de Contrataciones');
    DBMS_OUTPUT.PUT_LINE('----------------------------------------------------');

    FOR rec IN (
      WITH t AS (
        SELECT EXTRACT(MONTH FROM hire_date) mes_num,
               TO_CHAR(hire_date,'Month') mes_nombre,
               COUNT(employee_id) total_contrataciones
        FROM employees
        GROUP BY EXTRACT(YEAR FROM hire_date), EXTRACT(MONTH FROM hire_date), TO_CHAR(hire_date,'Month')
      )
      SELECT mes_nombre, AVG(total_contrataciones) promedio_mes
      FROM t
      GROUP BY mes_nombre, mes_num
      ORDER BY mes_num
    ) LOOP
      DBMS_OUTPUT.PUT_LINE(RPAD(rec.mes_nombre,15)||' | '||TO_CHAR(rec.promedio_mes,'99.00'));
      v_cnt_meses := v_cnt_meses + 1;
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('----------------------------------------------------');
    DBMS_OUTPUT.PUT_LINE('Total de meses en el listado: '||v_cnt_meses);
    RETURN v_cnt_meses;
  END fn_promedio_contrataciones;

  -- sp_resumen_regional: suma de salarios, conteo y fecha más antigua por región
  PROCEDURE sp_resumen_regional IS
    CURSOR c_reg IS
      SELECT r.region_name region,
             SUM(e.salary) salario_total,
             COUNT(e.employee_id) cantidad_empleados,
             MIN(e.hire_date) fecha_antiguo
      FROM regions r
      JOIN countries c USING(region_id)
      JOIN locations l USING(country_id)
      JOIN departments d USING(location_id)
      JOIN employees e USING(department_id)
      GROUP BY r.region_name;
  BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10)||'--- Reporte de Gastos y Estadística Regional ---');
    DBMS_OUTPUT.PUT_LINE('--------------------------------------------------------------------------------------------------');
    DBMS_OUTPUT.PUT_LINE('Región           | Suma Salarios   | Cantidad Empleados | Empleado Más Antiguo (Fecha Ingreso)');
    DBMS_OUTPUT.PUT_LINE('--------------------------------------------------------------------------------------------------');
    FOR r IN c_reg LOOP
      DBMS_OUTPUT.PUT_LINE(
        RPAD(r.region,17)||' | '||
        RPAD(TO_CHAR(r.salario_total,'FM999,999.00'),15)||' | '||
        RPAD(TO_CHAR(r.cantidad_empleados),18)||' | '||
        TO_CHAR(r.fecha_antiguo,'DD-MON-YYYY')
      );
    END LOOP;
  END sp_resumen_regional;

  -- fn_tiempo_servicio: lista años servicio y retorna total de meses de vacaciones
  FUNCTION fn_tiempo_servicio RETURN NUMBER IS
    v_total_meses NUMBER := 0;
  BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10)||'--- Tiempo de Servicio de Empleados ---');
    DBMS_OUTPUT.PUT_LINE('------------------------------------------------------------');
    DBMS_OUTPUT.PUT_LINE('Cod | Nombre Completo     | Años Servicio | Meses Vacaciones');
    DBMS_OUTPUT.PUT_LINE('------------------------------------------------------------');
    FOR r IN (
      SELECT employee_id codigo,
             first_name||' '||last_name nombre_completo,
             hire_date,
             MONTHS_BETWEEN(SYSDATE, hire_date)/12 anios_servicio,
             TRUNC(MONTHS_BETWEEN(SYSDATE, hire_date)/12) meses_vac
      FROM employees
      ORDER BY employee_id
    ) LOOP
      DBMS_OUTPUT.PUT_LINE(
        RPAD(r.codigo,3)||' | '||
        RPAD(r.nombre_completo,18)||' | '||
        RPAD(TO_CHAR(r.anios_servicio,'99.00'),22)||' | '||
        TO_CHAR(r.meses_vac)
      );
      v_total_meses := v_total_meses + r.meses_vac;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('------------------------------------------------------------');
    DBMS_OUTPUT.PUT_LINE('MONTO TOTAL EMPLEADO PARA EL TIEMPO DE SERVICIOS (MESES): '||v_total_meses);
    RETURN v_total_meses;
  END fn_tiempo_servicio;

  -- fn_horas_trabajadas_mes: total de horas reales trabajadas en un mes/año
  FUNCTION fn_horas_trabajadas_mes(p_employee_id INTEGER, p_month INTEGER, p_year INTEGER)
  RETURN NUMBER IS
    v_horas NUMBER;
  BEGIN
    SELECT SUM( (CAST(hora_termino_real AS DATE) - CAST(hora_inicio_real AS DATE)) * 24 )
    INTO v_horas
    FROM asistencia_empleado
    WHERE EXTRACT(MONTH FROM fecha_real) = p_month
      AND EXTRACT(YEAR  FROM fecha_real) = p_year
      AND employee_id = p_employee_id;
    RETURN NVL(v_horas,0);
  END fn_horas_trabajadas_mes;

  -- fn_horas_faltantes_mes: horas teóricas - horas reales (no negativo)
  FUNCTION fn_horas_faltantes_mes(p_employee_id IN NUMBER, p_mes IN NUMBER, p_anio IN NUMBER)
  RETURN NUMBER IS
    v_real        NUMBER;
    v_semana_hrs  NUMBER;
    v_mes_hrs     NUMBER;
    v_faltantes   NUMBER;
    v_dias_mes    NUMBER;
  BEGIN
    v_dias_mes := EXTRACT(DAY FROM LAST_DAY(TO_DATE(p_anio||'-'||p_mes,'YYYY-MM')));

    SELECT NVL(SUM(
             (EXTRACT(DAY FROM (NUMTODSINTERVAL(0,'MINUTE'))) * 24) +
             (TO_NUMBER(SUBSTR(h.hora_termino,1,2)) - TO_NUMBER(SUBSTR(h.hora_inicio,1,2))) +
             (TO_NUMBER(SUBSTR(h.hora_termino,4,2)) - TO_NUMBER(SUBSTR(h.hora_inicio,4,2))) / 60
           ), 0)
    INTO v_semana_hrs
    FROM empleado_horario eh
    JOIN horario h
      ON eh.dia_de_la_semana = h.dia_de_la_semana
     AND eh.turno = h.turno
    WHERE eh.employee_id = p_employee_id;

    v_semana_hrs := NVL(v_semana_hrs,0);
    v_mes_hrs    := v_semana_hrs * (v_dias_mes / 7);
    v_real       := fn_horas_trabajadas_mes(p_employee_id, p_mes, p_anio);
    v_faltantes  := v_mes_hrs - v_real;
    RETURN GREATEST(v_faltantes, 0);
  END fn_horas_faltantes_mes;

  -- sp_reporte_salarios_mes: calcula salario ajustado por horas faltantes
  PROCEDURE sp_reporte_salarios_mes(p_mes IN NUMBER, p_anio IN NUMBER) IS
    CURSOR c_emp IS
      SELECT employee_id codigo, first_name nombre, last_name apellido, salary salario
      FROM employees;
    v_faltas            NUMBER;
    v_semana_hrs        NUMBER;
    v_mes_hrs           NUMBER;
    v_valor_hora        NUMBER;
    v_salario_final     NUMBER;
    v_dias_mes          NUMBER;
  BEGIN
    v_dias_mes := TO_NUMBER(TO_CHAR(LAST_DAY(TO_DATE(p_anio||'-'||p_mes,'YYYY-MM')), 'DD'));
    DBMS_OUTPUT.PUT_LINE(CHR(10)||'--- REPORTE DE SALARIO AJUSTADO ('||p_mes||'/'||p_anio||') ---');
    DBMS_OUTPUT.PUT_LINE('--------------------------------------------------------------------------');
    DBMS_OUTPUT.PUT_LINE('Empleado              | Salario Base | Horas Faltadas | Salario Final');
    DBMS_OUTPUT.PUT_LINE('--------------------------------------------------------------------------');

    FOR r IN c_emp LOOP
      v_faltas := NVL(fn_horas_faltantes_mes(r.codigo, p_mes, p_anio),0);

      BEGIN
        SELECT NVL(SUM(
                 (TO_NUMBER(SUBSTR(h.hora_termino,1,2)) - TO_NUMBER(SUBSTR(h.hora_inicio,1,2))) +
                 (TO_NUMBER(SUBSTR(h.hora_termino,4,2)) - TO_NUMBER(SUBSTR(h.hora_inicio,4,2))) / 60
               ),0)
        INTO v_semana_hrs
        FROM empleado_horario eh
        JOIN horario h
          ON eh.dia_de_la_semana = h.dia_de_la_semana
         AND eh.turno = h.turno
        WHERE eh.employee_id = r.codigo;
      EXCEPTION
        WHEN NO_DATA_FOUND THEN
          v_semana_hrs := 0;
      END;

      v_mes_hrs := v_semana_hrs * (v_dias_mes / 7);

      IF v_mes_hrs <= 0 OR r.salario IS NULL THEN
        v_salario_final := NVL(r.salario,0);
      ELSE
        v_valor_hora := r.salario / v_mes_hrs;
        IF v_faltas > 0 THEN
          v_salario_final := r.salario - (v_faltas * v_valor_hora);
        ELSE
          v_salario_final := r.salario;
        END IF;
        v_salario_final := GREATEST(v_salario_final,0);
      END IF;

      DBMS_OUTPUT.PUT_LINE(
        RPAD(SUBSTR(r.nombre||' '||r.apellido,1,20),20)||' | '||
        RPAD(TO_CHAR(NVL(r.salario,0),'FM9,999.00'),12)||' | '||
        RPAD(TO_CHAR(v_faltas,'99.00'),14)||' | '||
        TO_CHAR(v_salario_final,'FM9,999.00')
      );
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('--------------------------------------------------------------------------');
  END sp_reporte_salarios_mes;

  -- fn_total_horas_capacitacion: total de horas de capacitación por empleado
  FUNCTION fn_total_horas_capacitacion(p_employee_id IN NUMBER) RETURN NUMBER IS
    v_total NUMBER;
  BEGIN
    SELECT NVL(SUM(c.horas_capacitacion),0)
    INTO v_total
    FROM empleado_capacitacion ec
    JOIN capacitacion c ON ec.capacitacion_id = c.capacitacion_id
    WHERE ec.employee_id = p_employee_id;
    RETURN v_total;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RETURN 0;
  END fn_total_horas_capacitacion;

  -- sp_listar_capacitaciones: lista empleados con horas totales (desc)
  PROCEDURE sp_listar_capacitaciones IS
  BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10)||'--- Capacitaciones y Horas por Empleado ---');
    DBMS_OUTPUT.PUT_LINE('---------------------------------------------------------');
    DBMS_OUTPUT.PUT_LINE('Empleado ID | Nombre Completo           | Horas Totales');
    DBMS_OUTPUT.PUT_LINE('---------------------------------------------------------');

    FOR r IN (
      SELECT e.employee_id,
             e.first_name||' '||e.last_name nombre_completo,
             NVL(SUM(c.horas_capacitacion),0) horas_totales
      FROM employees e
      LEFT JOIN empleado_capacitacion ec ON e.employee_id = ec.employee_id
      LEFT JOIN capacitacion c ON ec.capacitacion_id = c.capacitacion_id
      GROUP BY e.employee_id, e.first_name, e.last_name
      ORDER BY horas_totales DESC
    ) LOOP
      DBMS_OUTPUT.PUT_LINE(
        RPAD(r.employee_id,11)||' | '||
        RPAD(r.nombre_completo,24)||' | '||
        TO_CHAR(r.horas_totales,'FM9990')
      );
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('---------------------------------------------------------');
  END sp_listar_capacitaciones;

END PKG_EMPLOYEE_MGMT;
/

--------------------------------------------------------------------------------
-- Triggers
--------------------------------------------------------------------------------

-- trg_validar_asistencia_emp: valida día y correspondencia de horas con el horario
CREATE OR REPLACE TRIGGER trg_validar_asistencia_emp
BEFORE INSERT OR UPDATE ON asistencia_empleado
FOR EACH ROW
DECLARE
  v_weekday_name  VARCHAR2(20);
  v_weekday_num   VARCHAR2(1);
  v_cnt           NUMBER;
  v_inicio_ok     BOOLEAN := FALSE;
  v_termino_ok    BOOLEAN := FALSE;
BEGIN
  v_weekday_name := TRIM(UPPER(TO_CHAR(:NEW.fecha_real,'DAY','NLS_DATE_LANGUAGE=SPANISH')));
  v_weekday_num  := TO_CHAR(:NEW.fecha_real,'D');

  SELECT COUNT(*) INTO v_cnt
  FROM empleado_horario eh
  JOIN horario h ON (eh.dia_de_la_semana = h.dia_de_la_semana AND eh.turno = h.turno)
  WHERE eh.employee_id = :NEW.employee_id
    AND ( UPPER(h.dia_de_la_semana) = v_weekday_name OR h.dia_de_la_semana = v_weekday_num );

  IF v_cnt = 0 THEN
    RAISE_APPLICATION_ERROR(-20020, 'La fecha no corresponde al día del horario asignado.');
  END IF;

  FOR r IN (
    SELECT h.hora_inicio, h.hora_termino
    FROM empleado_horario eh
    JOIN horario h ON (eh.dia_de_la_semana = h.dia_de_la_semana AND eh.turno = h.turno)
    WHERE eh.employee_id = :NEW.employee_id
      AND ( UPPER(h.dia_de_la_semana) = v_weekday_name OR h.dia_de_la_semana = v_weekday_num )
  ) LOOP
    BEGIN
      DECLARE
        v_sched_start DATE;
        v_sched_end   DATE;
        v_reg_start   DATE := CAST(:NEW.hora_inicio_real AS DATE);
        v_reg_end     DATE := CAST(:NEW.hora_termino_real AS DATE);
      BEGIN
        v_sched_start := TO_DATE(TO_CHAR(:NEW.fecha_real,'YYYY-MM-DD')||' '||r.hora_inicio,  'YYYY-MM-DD HH24:MI:SS');
        v_sched_end   := TO_DATE(TO_CHAR(:NEW.fecha_real,'YYYY-MM-DD')||' '||r.hora_termino, 'YYYY-MM-DD HH24:MI:SS');

        IF ABS((v_reg_start - v_sched_start) * 24) <= 1 THEN v_inicio_ok := TRUE; END IF;
        IF ABS((v_reg_end   - v_sched_end  ) * 24) <= 1 THEN v_termino_ok := TRUE; END IF;
      END;
    EXCEPTION
      WHEN OTHERS THEN NULL;
    END;

    IF v_inicio_ok AND v_termino_ok THEN EXIT; END IF;
  END LOOP;

  IF NOT (v_inicio_ok AND v_termino_ok) THEN
    RAISE_APPLICATION_ERROR(-20021, 'Horas reales fuera de tolerancia con el horario asignado.');
  END IF;
END;
/

-- trg_validar_rango_salario: asegura que salary esté dentro del rango de JOBS
CREATE OR REPLACE TRIGGER trg_validar_rango_salario
BEFORE INSERT OR UPDATE ON employees
FOR EACH ROW
DECLARE
  v_min NUMBER;
  v_max NUMBER;
BEGIN
  SELECT min_salary, max_salary INTO v_min, v_max
  FROM jobs WHERE job_id = :NEW.job_id;

  IF :NEW.salary IS NULL THEN
    RAISE_APPLICATION_ERROR(-20030, 'El salario no puede ser NULL.');
  ELSIF :NEW.salary < v_min OR :NEW.salary > v_max THEN
    RAISE_APPLICATION_ERROR(-20031, 'Salario fuera del rango permitido para el puesto.');
  END IF;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR(-20032, 'Puesto (job_id) no encontrado en JOBS.');
END;
/

-- trg_registrar_inasistencia: marca en INASISTENCIAS_LOG si ingreso difiere > 30 min
CREATE OR REPLACE TRIGGER trg_registrar_inasistencia
BEFORE INSERT ON asistencia_empleado
FOR EACH ROW
DECLARE
  v_sched_start  DATE;
  v_reg_start    DATE;
  v_diff_min     NUMBER;
BEGIN
  SELECT TO_DATE(TO_CHAR(:NEW.fecha_real,'YYYY-MM-DD')||' '||h.hora_inicio,'YYYY-MM-DD HH24:MI:SS')
  INTO v_sched_start
  FROM empleado_horario eh
  JOIN horario h ON (eh.dia_de_la_semana = h.dia_de_la_semana AND eh.turno = h.turno)
  WHERE eh.employee_id = :NEW.employee_id
    AND (UPPER(h.dia_de_la_semana) = UPPER(TRIM(TO_CHAR(:NEW.fecha_real,'DAY','NLS_DATE_LANGUAGE=SPANISH')))
         OR h.dia_de_la_semana = TO_CHAR(:NEW.fecha_real,'D'))
    AND ROWNUM = 1;

  v_reg_start := CAST(:NEW.hora_inicio_real AS DATE);
  v_diff_min  := (v_reg_start - v_sched_start) * 24 * 60;

  IF ABS(v_diff_min) > 30 THEN
    INSERT INTO inasistencias_log(employee_id, fecha, hora_registro, hora_esperada, diferencia_min, motivo)
    VALUES(:NEW.employee_id, TRUNC(:NEW.fecha_real), SYSTIMESTAMP, TO_CHAR(v_sched_start,'HH24:MI:SS'),
           v_diff_min, 'Registro fuera de ventana +/-30 min');
  END IF;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    NULL;
  WHEN OTHERS THEN
    NULL;
END;
/
